export const Players = 
    [
        {
            "id": "1",
            "playerName": "Eoin Morgan ",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "10",
            "role": "Batsman ",
            "rating": "90",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/24598.jpg"
        },
        {
            "id": "2",
            "playerName": "Andre Russell",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "15",
            "role": "All Rounder",
            "rating": "95",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/276298.jpg"
        },
        {
            "id": "3",
            "playerName": "Dinesh Kartik ",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "10",
            "role": "Batsman (wk)",
            "rating": "86",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/30045.jpg"
        },
        {
            "id": "4",
            "playerName": "Harbhajan Singh",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "76",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/29264.jpg"
        },
        {
            "id": "5",
            "playerName": "Kamlesh Nagarkoti",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "79",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/1070188.jpg"
        },
        {
            "id": "6",
            "playerName": "Kuldeep Yadav",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "81",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/559235.jpg"
        },
        {
            "id": "7",
            "playerName": "Lockie Ferguson ",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "91",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": " https://www.cricapi.com/playerpic/493773.jpg"
        },
        {
            "id": "8",
            "playerName": "Nitish Rana ",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "10",
            "role": "Batsman",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/604527.jpg"
        },
        {
            "id": "9",
            "playerName": "Pat Cummins ",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "15",
            "role": "Bowler",
            "rating": "93",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/489889.jpg"
        },
        {
            "id": "10",
            "playerName": "Shakib Al Hasan ",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "5",
            "role": "All Rounder",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": " https://www.cricapi.com/playerpic/56143.jpg"
        },
        {
            "id": "11",
            "playerName": "Shubman Gill",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "10",
            "role": "Batsman",
            "rating": "88",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/1070173.jpg"
        },
        {
            "id": "12",
            "playerName": "Sunil Narine ",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "10",
            "role": "All Rounder",
            "rating": "86",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/230558.jpg"
        },
        {
            "id": "13",
            "playerName": "Ben Cutting ",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "5",
            "role": "All Rounder",
            "rating": "82",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/230371.jpg"
        },
        {
            "id": "14",
            "playerName": "Varun Chakravarthy",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5"
        },
        {
            "id": "15",
            "playerName": "Rahul Tripath (wk)",
            "teamName": "Kolkata Knight Riders",
            "basePrice": "5",
            "role": "Batsman(wk)",
            "rating": "82",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/446763.jpg"
        },
        {
            "id": "16",
            "playerName": "ROHIT SHARMA",
            "teamName": "Mumbai Indians",
            "basePrice": "20",
            "role": "BATSMAN",
            "rating": "97",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/34102.jpg"
        },
        {
            "id": "17",
            "playerName": "QUINTON DE KOCK ",
            "teamName": "Mumbai Indians",
            "basePrice": "10",
            "role": "WICKET-KEEPER",
            "rating": "86",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/379143.jpg"
        },
        {
            "id": "18",
            "playerName": "SURYAKUMAR YADAV",
            "teamName": "Mumbai Indians",
            "basePrice": "10",
            "role": "BATSMAN",
            "rating": "87",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/446507.jpg"
        },
        {
            "id": "19",
            "playerName": "ISHAN KISHAN",
            "teamName": "Mumbai Indians",
            "basePrice": "10",
            "role": "WICKET KEEPER",
            "rating": "87",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/720471.jpg"
        },
        {
            "id": "20",
            "playerName": "KIERON POLLARD ",
            "teamName": "Mumbai Indians",
            "basePrice": "15",
            "role": "ALL-ROUNDER",
            "rating": "92",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/230559.jpg"
        },
        {
            "id": "21",
            "playerName": "HARDIK PANDYA",
            "teamName": "Mumbai Indians",
            "basePrice": "15",
            "role": "ALL-ROUNDER",
            "rating": "93",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/625371.jpg"
        },
        {
            "id": "22",
            "playerName": "KRUNAL PANDYA",
            "teamName": "Mumbai Indians",
            "basePrice": "10",
            "role": "ALL-ROUNDER",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/471342.jpg"
        },
        {
            "id": "23",
            "playerName": "RAHUL CHAHAR",
            "teamName": "Mumbai Indians",
            "basePrice": "10",
            "role": "BOWLER",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/1064812.jpg"
        },
        {
            "id": "24",
            "playerName": "ADAM MILNE ",
            "teamName": "Mumbai Indians",
            "basePrice": "10",
            "role": "BOWLER",
            "rating": "80",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/450860.jpg"
        },
        {
            "id": "25",
            "playerName": "TRENT BOULT ",
            "teamName": "Mumbai Indians",
            "basePrice": "15",
            "role": "BOWLER",
            "rating": "91",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/277912.jpg"
        },
        {
            "id": "26",
            "playerName": "JASPRIT BUMRAH",
            "teamName": "Mumbai Indians",
            "basePrice": "20",
            "role": "BOWLER",
            "rating": "98",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/625383.jpg"
        },
        {
            "id": "27",
            "playerName": "CHRIS LYNN ",
            "teamName": "Mumbai Indians",
            "basePrice": "10",
            "role": "BATSMAN",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/326637.jpg"
        },
        {
            "id": "28",
            "playerName": "JIMMY NEESHAM (O)",
            "teamName": "Mumbai Indians",
            "basePrice": "10",
            "role": "ALL-ROUNDER",
            "rating": "83",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/355269.jpg"
        },
        {
            "id": "29",
            "playerName": "ARJUN TENDULKAR",
            "teamName": "Mumbai Indians",
            "basePrice": "5",
            "role": "ALL-ROUNDER",
            "rating": "72",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/1148776.jpg"
        },
        {
            "id": "30",
            "playerName": "PIYUSH CHAWLA",
            "teamName": "Mumbai Indians",
            "basePrice": "5",
            "role": "BOWLER",
            "rating": "79",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/32966.jpg"
        },
        {
            "id": "31",
            "playerName": "MS DHONI",
            "teamName": "Chennai Super Kings",
            "basePrice": "15",
            "role": "WK-BATSMAN",
            "rating": "93",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/28081.jpg"
        },
        {
            "id": "32",
            "playerName": "ROBIN UTHAPPA",
            "teamName": "Chennai Super Kings",
            "basePrice": "5",
            "role": "WK-BATSMAN",
            "rating": "79",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/35582.jpg"
        },
        {
            "id": "33",
            "playerName": "RUTURAJ GAIKWAD",
            "teamName": "Chennai Super Kings",
            "basePrice": "10",
            "role": "BATSMAN",
            "rating": "83",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/1060380.jpg"
        },
        {
            "id": "34",
            "playerName": "FAF DU PLESSIS",
            "teamName": "Chennai Super Kings",
            "basePrice": "15",
            "role": "BATSMAN",
            "rating": "90",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/44828.jpg"
        },
        {
            "id": "35",
            "playerName": "SURESH RAINA",
            "teamName": "Chennai Super Kings",
            "basePrice": "10",
            "role": "BATSMAN",
            "rating": "91",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/33335.jpg"
        },
        {
            "id": "36",
            "playerName": "AMBATI RAYDU",
            "teamName": "Chennai Super Kings",
            "basePrice": "10",
            "role": "BATSMAN",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/33141.jpg"
        },
        {
            "id": "37",
            "playerName": "RAVINDRA JADEJA",
            "teamName": "Chennai Super Kings",
            "basePrice": "15",
            "role": "ALL ROUNDER",
            "rating": "92",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/234675.jpg"
        },
        {
            "id": "38",
            "playerName": "SAM CURRAN",
            "teamName": "Chennai Super Kings",
            "basePrice": "15",
            "role": "ALL ROUNDER",
            "rating": "90",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/662973.jpg"
        },
        {
            "id": "39",
            "playerName": "MOEEN ALI",
            "teamName": "Chennai Super Kings",
            "basePrice": "10",
            "role": "ALL ROUNDER",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/8917.jpg"
        },
        {
            "id": "40",
            "playerName": "DWAYNE BRAVO",
            "teamName": "Chennai Super Kings",
            "basePrice": "10",
            "role": "ALL ROUNDER",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/51439.jpg"
        },
        {
            "id": "41",
            "playerName": "SHARDUL THAKUR",
            "teamName": "Chennai Super Kings",
            "basePrice": "15",
            "role": "ALL ROUNDER",
            "rating": "89",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/475281.jpg"
        },
        {
            "id": "42",
            "playerName": "DEEPAK CHAHAR",
            "teamName": "Chennai Super Kings",
            "basePrice": "10",
            "role": "BOWLER",
            "rating": "83",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/447261.jpg"
        },
        {
            "id": "43",
            "playerName": "IMRAN TAHIR",
            "teamName": "Chennai Super Kings",
            "basePrice": "10",
            "role": "BOWLER",
            "rating": "83",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/40618.jpg"
        },
        {
            "id": "44",
            "playerName": "LUNGI NGIDI",
            "teamName": "Chennai Super Kings",
            "basePrice": "5",
            "role": "BOWLER",
            "rating": "78",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/542023.jpg"
        },
        {
            "id": "45",
            "playerName": "N JAGADEESAN",
            "teamName": "Chennai Super Kings",
            "basePrice": "5",
            "role": "BATSMAN",
            "rating": "74",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/1048813.jpg"
        },
        {
            "id": "46",
            "playerName": "KRISHNAPPA GOWTHAM",
            "teamName": "Chennai Super Kings",
            "basePrice": "10",
            "role": "ALL ROUNDER",
            "rating": "80",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/424377.jpg"
        },
        {
            "id": "47",
            "playerName": "CHETESHWAR PUJARA",
            "teamName": "Chennai Super Kings",
            "basePrice": "5",
            "role": "BATSMAN",
            "rating": "77",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/32540.jpg"
        },
        {
            "id": "48",
            "playerName": "Kagiso rabada (o)",
            "teamName": "Delhi Capitals",
            "basePrice": "20",
            "role": "Bowler",
            "rating": "98",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/550215.jpg"
        },
        {
            "id": "49",
            "playerName": "Rishab Pant",
            "teamName": "Delhi Capitals",
            "basePrice": "20",
            "role": "Wicket Keeper",
            "rating": "96",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/931581.jpg"
        },
        {
            "id": "50",
            "playerName": "Amit Mishra",
            "teamName": "Delhi Capitals",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "87",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/31107.jpg"
        },
        {
            "id": "51",
            "playerName": "Marcus Stoinis (o)",
            "teamName": "Delhi Capitals",
            "basePrice": "15",
            "role": "Allrounder",
            "rating": "90",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/325012.jpg"
        },
        {
            "id": "52",
            "playerName": "R Ashwin",
            "teamName": "Delhi Capitals",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "86",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/26421.jpg"
        },
        {
            "id": "53",
            "playerName": "Axar Patel",
            "teamName": "Delhi Capitals",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/554691.jpg"
        },
        {
            "id": "54",
            "playerName": "Shimron Hetmyer (o)",
            "teamName": "Delhi Capitals",
            "basePrice": "10",
            "role": "Allrounder",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/670025.jpg"
        },
        {
            "id": "55",
            "playerName": "Prithvi Shaw",
            "teamName": "Delhi Capitals",
            "basePrice": "10",
            "role": "Batsmen",
            "rating": "81",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/1070168.jpg"
        },
        {
            "id": "56",
            "playerName": "Tom Curran(o)",
            "teamName": "Delhi Capitals",
            "basePrice": "10",
            "role": "Batsmen",
            "rating": "80",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/550235.jpg"
        },
        {
            "id": "57",
            "playerName": "Steve Smith (o)",
            "teamName": "Delhi Capitals",
            "basePrice": "10",
            "role": "Batsmen",
            "rating": "87",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": " https://www.cricapi.com/playerpic/267192.jpg"
        },
        {
            "id": "58",
            "playerName": "Anrich Nortje (o)",
            "teamName": "Delhi Capitals",
            "basePrice": "15",
            "role": "Bowler",
            "rating": "90",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/481979.jpg"
        },
        {
            "id": "59",
            "playerName": "Chris Woakes (o)",
            "teamName": "Delhi Capitals",
            "basePrice": "10",
            "role": "Allrounder",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/247235.jpg"
        },
        {
            "id": "60",
            "playerName": "Vishnu Vinod",
            "teamName": "Delhi Capitals",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "79",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/732293.jpg"
        },
        {
            "id": "61",
            "playerName": "Avesh Khan",
            "teamName": "Delhi Capitals",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "78",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5"
        },
        {
            "id": "62",
            "playerName": "Praveen Dubey",
            "teamName": "Delhi Capitals",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "77",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5"
        },
        {
            "id": "63",
            "playerName": "Shikhar Dhawan",
            "teamName": "Delhi Capitals",
            "basePrice": "15",
            "role": "Batsmen",
            "rating": "91",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/28235.jpg"
        },
        {
            "id": "64",
            "playerName": "Sanju Samson(C)",
            "teamName": "Rajasthan Royals",
            "basePrice": "10",
            "role": "Wicket Keeper",
            "rating": "86",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/425943.jpg"
        },
        {
            "id": "65",
            "playerName": "Andrew Tye",
            "teamName": "Rajasthan Royals",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/459508.jpg"
        },
        {
            "id": "66",
            "playerName": "Jos Buttler",
            "teamName": "Rajasthan Royals",
            "basePrice": "15",
            "role": "Wicket Keeper",
            "rating": "91",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/526440.jpg"
        },
        {
            "id": "67",
            "playerName": "Ben Stokes",
            "teamName": "Rajasthan Royals",
            "basePrice": "20",
            "role": "Allrounder",
            "rating": "97",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/311158.jpg"
        },
        {
            "id": "68",
            "playerName": "Jofra Archer",
            "teamName": "Rajasthan Royals",
            "basePrice": "20",
            "role": "Bowler",
            "rating": "97",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/669855.jpg"
        },
        {
            "id": "69",
            "playerName": "Chris Morris",
            "teamName": "Rajasthan Royals",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "86",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/439952.jpg"
        },
        {
            "id": "70",
            "playerName": "David Miller",
            "teamName": "Rajasthan Royals",
            "basePrice": "10",
            "role": "Batsman",
            "rating": "82",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/321777.jpg"
        },
        {
            "id": "71",
            "playerName": "Jaydev Unadkat",
            "teamName": "Rajasthan Royals",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "79",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/390484.jpg"
        },
        {
            "id": "72",
            "playerName": "Rahul Tewatia",
            "teamName": "Rajasthan Royals",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "88",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/423838.jpg"
        },
        {
            "id": "73",
            "playerName": "Shreyas Gopal",
            "teamName": "Rajasthan Royals",
            "basePrice": "10",
            "role": "Allrounder",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/344580.jpg"
        },
        {
            "id": "74",
            "playerName": "Mayank Markande",
            "teamName": "Rajasthan Royals",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "78",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://static.toiimg.com/thumb/msid-68047519,imgsize-99998,width-400,resizemode-4/68047519.jpg"
        },
        {
            "id": "75",
            "playerName": "Manan Vohra",
            "teamName": "Rajasthan Royals",
            "basePrice": "5",
            "role": "Batsman",
            "rating": "79",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/532856.jpg"
        },
        {
            "id": "76",
            "playerName": "Mustafizur Rahman",
            "teamName": "Rajasthan Royals",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "83",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/330902.jpg"
        },
        {
            "id": "77",
            "playerName": "Shivam Dube",
            "teamName": "Rajasthan Royals",
            "basePrice": "5",
            "role": "Allrounder",
            "rating": "78",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/714451.jpg"
        },
        {
            "id": "78",
            "playerName": "Basil Thampi",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "78",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/732291.jpg"
        },
        {
            "id": "79",
            "playerName": "Jonny Bairstow",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "15",
            "role": "Wicket Keeper-Batsman",
            "rating": "90",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/297433.jpg"
        },
        {
            "id": "80",
            "playerName": "Bhuvneshwar Kumar",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "15",
            "role": "Bowler",
            "rating": "92",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/326016.jpg"
        },
        {
            "id": "81",
            "playerName": "Wriddhiman Saha",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "10",
            "role": "Wicket Keeper",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/279810.jpg"
        },
        {
            "id": "82",
            "playerName": "Kedar Jadhav",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "10",
            "role": "Allrounder",
            "rating": "83",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/290716.jpg"
        },
        {
            "id": "83",
            "playerName": "Rashid Khan",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "20",
            "role": "Allrounder",
            "rating": "96",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/793463.jpg"
        },
        {
            "id": "84",
            "playerName": "Kane Willamson",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "15",
            "role": "Batsman",
            "rating": "91",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/277906.jpg"
        },
        {
            "id": "85",
            "playerName": "Manish Pandey",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "10",
            "role": "Batsman",
            "rating": "89",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/290630.jpg"
        },
        {
            "id": "86",
            "playerName": "Siddarth Kaul",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "79",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/326017.jpg"
        },
        {
            "id": "87",
            "playerName": "Mohammad Nabi",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "10",
            "role": "Allrounder",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/1058993.jpg"
        },
        {
            "id": "88",
            "playerName": "Priyam Garg",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "10",
            "role": "Batsman",
            "rating": "81",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10"
        },
        {
            "id": "89",
            "playerName": "Sandeep Sharma",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "77",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/438362.jpg"
        },
        {
            "id": "90",
            "playerName": "Jason Holder",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "15",
            "role": "Allrounder",
            "rating": "91",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/391485.jpg"
        },
        {
            "id": "91",
            "playerName": "T Natarajan",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "88",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/802575.jpg"
        },
        {
            "id": "92",
            "playerName": "Virat Singh",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "5",
            "role": "Batsman",
            "rating": "80",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/720465.jpg"
        },
        {
            "id": "93",
            "playerName": "David Warner",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "20",
            "role": "Batsman",
            "rating": "98",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/219889.jpg"
        },
        {
            "id": "94",
            "playerName": "Abhishek Sharma",
            "teamName": "Sunrisers Hyderabad",
            "basePrice": "5",
            "role": "Batsman",
            "rating": "81",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/1070183.jpg"
        },
        {
            "id": "95",
            "playerName": "Virat Kohli",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "20",
            "role": "Batsman",
            "rating": "99",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/253802.jpg"
        },
        {
            "id": "96",
            "playerName": "AB De Villiers",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "20",
            "role": "Batsman",
            "rating": "98",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/44936.jpg"
        },
        {
            "id": "97",
            "playerName": "Yuzvendra Chahal",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "15",
            "role": "Bowler",
            "rating": "90",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/430246.jpg"
        },
        {
            "id": "98",
            "playerName": "Washington Sundar",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/719715.jpg"
        },
        {
            "id": "99",
            "playerName": "Mohammed Siraj",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/940973.jpg"
        },
        {
            "id": "100",
            "playerName": "Adam Zampa",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/379504.jpg"
        },
        {
            "id": "101",
            "playerName": "Glenn Maxwell",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "10",
            "role": "All-Rounder",
            "rating": "87",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/325026.jpg"
        },
        {
            "id": "102",
            "playerName": "Devdutt Padikkal",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "10",
            "role": "Batsman",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "null"
        },
        {
            "id": "103",
            "playerName": "Navdeep Saini",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "85",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/700167.jpg"
        },
        {
            "id": "104",
            "playerName": "Shahbaz Ahmed",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "75",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5"
        },
        {
            "id": "105",
            "playerName": "Pavan Deshpande",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "5",
            "role": "Batsman",
            "rating": "78",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "null"
        },
        {
            "id": "106",
            "playerName": "Sachin Baby",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "5",
            "role": "Batsman",
            "rating": "75",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/432783.jpg"
        },
        {
            "id": "107",
            "playerName": "Dan Christian",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "10",
            "role": "All-Rounder",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/4864.jpg"
        },
        {
            "id": "108",
            "playerName": "KS Bharat",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "5",
            "role": "Wicketkeeper",
            "rating": "74",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5"
        },
        {
            "id": "109",
            "playerName": "Daniel Sams",
            "teamName": "Royal Challengers Bangalore",
            "basePrice": "10",
            "role": "All-Rounder",
            "rating": "83",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/826901.jpg"
        },
        {
            "id": "110",
            "playerName": "Mayank Agarwal",
            "teamName": "Kings XI Punjab",
            "basePrice": "15",
            "role": "Batsmen",
            "rating": "92",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/398438.jpg"
        },
        {
            "id": "111",
            "playerName": "Dawid Malan",
            "teamName": "Kings XI Punjab",
            "basePrice": "15",
            "role": "batsmen",
            "rating": "89",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/236489.jpg"
        },
        {
            "id": "112",
            "playerName": "Fabian Allen",
            "teamName": "Kings XI Punjab",
            "basePrice": "10",
            "role": "Allrounder",
            "rating": "84",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/670013.jpg"
        },
        {
            "id": "113",
            "playerName": "Deepak Hooda",
            "teamName": "Kings XI Punjab",
            "basePrice": "5",
            "role": "all rounder",
            "rating": "81",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/497121.jpg"
        },
        {
            "id": "114",
            "playerName": "Nicholas Pooran",
            "teamName": "Kings XI Punjab",
            "basePrice": "10",
            "role": "wicket keeper / batsmen",
            "rating": "87",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/604302.jpg"
        },
        {
            "id": "115",
            "playerName": "arshdeep Singh",
            "teamName": "Kings XI Punjab",
            "basePrice": "5",
            "role": "bowler",
            "rating": "80",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5"
        },
        {
            "id": "116",
            "playerName": "Murugan Ashwin",
            "teamName": "Kings XI Punjab",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "82",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/528067.jpg"
        },
        {
            "id": "117",
            "playerName": "Md. Shami",
            "teamName": "Kings XI Punjab",
            "basePrice": "15",
            "role": "Bowler",
            "rating": "91",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/481896.jpg"
        },
        {
            "id": "118",
            "playerName": "Ravi Bishnoi",
            "teamName": "Kings XI Punjab",
            "basePrice": "10",
            "role": "Bowler",
            "rating": "86",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10"
        },
        {
            "id": "119",
            "playerName": "Riley Meredith",
            "teamName": "Kings XI Punjab",
            "basePrice": "5",
            "role": "Bowler",
            "rating": "80",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/961713.jpg"
        },
        {
            "id": "120",
            "playerName": "Chris Gayle",
            "teamName": "Kings XI Punjab",
            "basePrice": "15",
            "role": "Batsmen",
            "rating": "89",
            "soldTo": "none",
            "status": "none",
            "currentBid": "15",
            "image_url": "https://www.cricapi.com/playerpic/51880.jpg"
        },
        {
            "id": "121",
            "playerName": "KL Rahul",
            "teamName": "Kings XI Punjab",
            "basePrice": "20",
            "role": "Wicket Keeper/Captain",
            "rating": "97",
            "soldTo": "none",
            "status": "none",
            "currentBid": "20",
            "image_url": "https://www.cricapi.com/playerpic/422108.jpg"
        },
        {
            "id": "122",
            "playerName": "Sarfaraz Khan",
            "teamName": "Kings XI Punjab",
            "basePrice": "5",
            "role": "Batsmen",
            "rating": "81",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/642525.jp"
        },
        {
            "id": "123",
            "playerName": "Moises Henriques",
            "teamName": "Kings XI Punjab",
            "basePrice": "10",
            "role": "all rounder",
            "rating": "86",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/5961.jpg"
        },
        {
            "id": "124",
            "playerName": "Chris Jordan",
            "teamName": "Kings XI Punjab",
            "basePrice": "10",
            "role": "bowler",
            "rating": "83",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/288992.jpg"
        },
        {
            "id": "125",
            "playerName": "Mandeep Singh",
            "teamName": "Kings XI Punjab",
            "basePrice": "5",
            "role": "all rounder",
            "rating": "77",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/398506.jpg"
        },
        {
            "id": "126",
            "playerName": "Ishan Porel",
            "teamName": "Kings XI Punjab",
            "basePrice": "5",
            "role": "bowler",
            "rating": "76",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/967603.jpg"
        },
        {
            "id": "127",
            "playerName": "Jhye Richardson",
            "teamName": "Kings XI Punjab",
            "basePrice": "10",
            "role": "Bowler ",
            "rating": "83",
            "soldTo": "none",
            "status": "none",
            "currentBid": "10",
            "image_url": "https://www.cricapi.com/playerpic/774223.jpg"
        },
        {
            "id": "128",
            "playerName": "Shah Ruk Khan",
            "teamName": "Kings XI Punjab",
            "basePrice": "5",
            "role": "Batsmen (extra)",
            "rating": "80",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5",
            "image_url": "https://www.cricapi.com/playerpic/719719.jpg"
        },
        {
            "id": "129",
            "playerName": "Utkarsh Singh",
            "teamName": "Kings XI Punjab",
            "basePrice": "5",
            "role": "All rounder (extra)",
            "rating": "74",
            "soldTo": "none",
            "status": "none",
            "currentBid": "5"
        }
    ]
